# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TCBFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'Alamofire', '5.6.1'
  pod 'lottie-ios', "~> 3.4.4"
  pod 'Starscream', '~> 4.0.0'
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'ObjectMapper', '~> 4.2.0'
  pod 'SwifterSwift', '~> 5.2.0'
  pod 'YouTubePlayer'


  target 'TCBFrameworkTests' do
    # Pods for testing
  end

end
